<?
$aMenuLinks = Array(
	Array(
		"Водоснабжение", 
		"/engineering_systems/water_supply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Водоотведение", 
		"/engineering_systems/water_disposal/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Отопление", 
		"/engineering_systems/heating/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Теплоснабжение и вентиляция", 
		"/engineering_systems/heat_supply_ventilation/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Холодоснабжение", 
		"/engineering_systems/cold_supply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ИТП и ЦТП", 
		"/engineering_systems/itp_ctp/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Котельные", 
		"/engineering_systems/boiler_rooms/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Пожаротушение", 
		"/engineering_systems/firefighting/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>